name: Deploy to DigitalOcean (Development)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa_do_rigfab_github_actions
          chmod 600 ~/.ssh/id_rsa_do_rigfab_github_actions

      - name: Deploy to DigitalOcean
        run: |
          ssh -i ~/.ssh/id_rsa_do_rigfab_github_actions -o StrictHostKeyChecking=no root@${{ vars.DROPLET_IP }} 'bash -s' <<'EOF'

          cd ~/apps/practice-ci-cd
          git checkout development
          git pull origin development
          npm install
          npm run build

          pm2 stop practice-ci-cd-development || true
          pm2 start npm --name "practice-ci-cd-development" -- run start:dev -- -p 3002
          EOF
