name: Deploy to DigitalOcean (Master)

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa_do_rigfab_github_actions
          chmod 600 ~/.ssh/id_rsa_do_rigfab_github_actions

      - name: Deploy to DigitalOcean
        run: |
          ssh -i ~/.ssh/id_rsa_do_rigfab_github_actions -o StrictHostKeyChecking=no root@${{ vars.DROPLET_IP }} 'bash -s' <<'EOF'

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa_do_rigfab_github_actions
          source ~/.nvm/nvm.sh
          nvm use 22.4.1
          cd ~/apps/practice-ci-cd
          git checkout master

          git pull origin master
          npm install
          npm run build

          pm2 stop practice-ci-cd-master || true
          pm2 start npm --name "practice-ci-cd-master" -- run start -- -p 3000
          EOF
